### ISSUE TITLE
Request for the classification code

### ISSUE THREAD

**Issue by Moon-usyd** [billhhh/ShaSpec#11]
Hi, your work about missing modality is pretty nice.  And I have a grest interest in the code of classification part. Could u please consider releasing that part of the code? I will greatly appreciate it!

**Comment by Mannix-D** [comment]
I have the same questions as you.

**Comment by billhhh** [comment]
Thank you for your questions. Currently, we release the code version on Brats but do not have plans for Audiovision-MNIST data, as Brats have much more influence on the field. The same question we answered here https://github.com/billhhh/ShaSpec/issues/9

**Comment by billhhh** [comment]
Close the issue for now, if you have more questions, feel free to ask
