### ISSUE TITLE
Discrepancy in general_shared_ft Calculation

### ISSUE THREAD

**Issue by Ho-Garfield** [billhhh/ShaSpec#12]
Hi,we noticed a discrepancy between the calculation of general_shared_ft in the code and the method described in the original paper. 

```python    
general_shared_ft = shared_ft[mode_split[0]:N * C + 1:C]  # take the 1st available mode for shared fts
# general_shared_ft = 0  # average available shared fts
# for m in mode_split: general_shared_ft += shared_ft[m:N * C + 1:C]
# general_shared_ft /= len(mode_split)
```
![image](https://github.com/user-attachments/assets/b3c9310f-e0ab-4a8c-9dd4-cc2135547b3d)
The approach in the original paper seems more aligned with the commented-out code block. Could you please advise on which one we should use?

**Comment by billhhh** [comment]
Hello, thank you for your question and interested in our work.
In short, both would work, the current uncommented one is used for simplicity.

Similar question can be referred to https://github.com/billhhh/ShaSpec/issues/4

**Comment by billhhh** [comment]
Close the issue for now, if you have more questions, feel free to ask
