### ISSUE TITLE
Problems in Eval

### ISSUE THREAD

**Issue by fybgogogo** [billhhh/ShaSpec#2]
I think there is an issue with my training results. The output after eval is completely different from the result of tumor segmentation, but I don't know what the problem is with my operation. In outputs, there are basically only some white dots, and the desired results cannot be seen. 
![1](https://github.com/billhhh/ShaSpec/assets/117004851/2c008891-1410-4580-95d7-98358b2ccc31)
![2](https://github.com/billhhh/ShaSpec/assets/117004851/b410045b-09d9-44ad-b1cb-c00675636b0f)

**Comment by billhhh** [comment]
Hello, can you try the samples from training set, see if it is well trained?
Also, may I know if all cases perfom the same in the evaluation set?

Another thing you can try is to train more iterations, see if it helps.

**Comment by billhhh** [comment]
Oh, I think I know the reason: If you only trained 80000 iters with full modalities and eval with the default eval.sh, as now the model only see full modalities, but in the eval.sh, only --mode=1 is available by default, there is a gap between training and testing. So you either evaluate the model with --mode=0,1,2,3 now or you need to complete the other random drop modality training and evaluate the model again. To evaluate all different combination as in the paper, you should finish the random drop training.

**Comment by fybgogogo** [comment]
Thank you. I have obtained the segmentation result according to your method.

**Comment by billhhh** [comment]
cool
