### ISSUE TITLE
您好，所以评估和训练是都用了DCO和DAO这两个辅助任务吗

### ISSUE THREAD

**Issue by aixuanjiayi** [billhhh/ShaSpec#3]
如题，看论文训练和评估是分开写的，但是图又是一起画的有点拿不准，代码看起来貌似也是都用了，想问一个准确答案，谢谢

**Comment by billhhh** [comment]
你好，感谢对项目的兴趣。DCO和DAO是两个 objective function，只在 training 的时候作为 loss 使用，evaluate 的时候不用。

**Comment by billhhh** [comment]
I close the issue for now. If you have more questions, feel free to ask

**Comment by aixuanjiayi** [comment]
您好，我运行bash run.sh 0命令显示


这个错误，我直接运行python train_ss.py，出现


这个错误，我的CUDA版本是12.2，服务器是3090，匹配不了过低版本的torch，请问还有什么解决办法吗，functional.py的_verify_batch_size(input.size())这句话我也已经注释掉了，还是出现了上面的错误。
&nbsp; &nbsp; &nbsp; 求问解决办法，谢谢！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "billhhh/ShaSpec"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月28日(星期五) 下午2:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [billhhh/ShaSpec] 您好，所以评估和训练是都用了DCO和DAO这两个辅助任务吗 (Issue #3)





 
Closed #3 as completed.

**Comment by billhhh** [comment]
> 您好，我运行bash run.sh 0命令显示 这个错误，我直接运行python train_ss.py，出现 这个错误，我的CUDA版本是12.2，服务器是3090，匹配不了过低版本的torch，请问还有什么解决办法吗，functional.py的_verify_batch_size(input.size())这句话我也已经注释掉了，还是出现了上面的错误。 &nbsp; &nbsp; &nbsp; 求问解决办法，谢谢！ ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "billhhh/ShaSpec" ***@***.***&gt;; 发送时间:&nbsp;2024年6月28日(星期五) 下午2:15 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [billhhh/ShaSpec] 您好，所以评估和训练是都用了DCO和DAO这两个辅助任务吗 (Issue #3) Closed #3 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，感谢对项目感兴趣，用 conda 的虚拟环境可以安装特定版本的 cuda
