### ISSUE TITLE
code of Audiovision-MNIST classification

### ISSUE THREAD

**Issue by FT-ZHOU-ZZZ** [billhhh/ShaSpec#6]
Hi, thanks for your impressive work.
I will appreciate if you can provide the code for Audiovision-MNIST classification.
Thanks for your time!

**Comment by billhhh** [comment]
Thank you for your interest. Currently, we release the code version on Brats, as Brats have much more influence on the field.

**Comment by FT-ZHOU-ZZZ** [comment]
Is there any plan or possibility to release the classification codes? 
The current version is only applicable to homogeneous multimodal data (i.e. multi sequence MRI), but not to heterogeneous multimodal data such as tabular data, pathological image, radiology image, etc.
The current version (only segmentation task) has limited applications in multimodal learning with missing modality, not only in traditional CV domain but also in healthcare domain.
So, I think the classification code is more important to heterogeneous multimodal data.
I'm looking forward to the release of classification code.
Thanks!

**Comment by billhhh** [comment]
Thanks, we will keep it in mind and let you know. But for now, I have not orgainized the code :)

**Comment by billhhh** [comment]
So I kept it close for now, let me know if you have further questions.
