### ISSUE TITLE
online evaluation of the BraTS2018

### ISSUE THREAD

**Issue by HYC01** [billhhh/ShaSpec#8]
Is there an access issues with the website for online evaluation of the BraTS2018 dataset, which is https://ipp.cbica.upenn.edu/.

**Comment by billhhh** [comment]
Hi HYC01,

Yes, I cannot access the site as well.
It can be accessed one week ago. Hopefully it can be fixed soon.

Best

**Comment by billhhh** [comment]
> Is there an access issues with the website for online evaluation of the BraTS2018 dataset, which is https://ipp.cbica.upenn.edu/.

Just tried, can be accessed now
