### ISSUE TITLE
shared encoder on the Audiovision-MNIST dataset

### ISSUE THREAD

**Issue by HYC01** [billhhh/ShaSpec#9]
The code you provided offers detailed implementation based on the Brats18 dataset, which I found very helpful. However, I am particularly interested in your experimental details on the Audiovision-MNIST dataset. Specifically, I am keen to understand how to construct the shared encoder when dealing with two modalities (image and audio) that have different data dimensions.

**Comment by billhhh** [comment]
Thank you for your interest. Currently, we release the code version on Brats but do not have plans for Audiovision-MNIST data, as Brats have much more influence on the field. For dealing with 2 modalities, if one is missing, we can use the available one feature to replace the missing one.
